INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_MODERATOR');

//TOKEN DI PROVA
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcm92YUBnbWFpbC5jb20iLCJpYXQiOjE3MzgxNjMyNTAsImV4cCI6MTc2OTY5OTI1MH0.sp5d7SpZsRqfG3Q7Fj2ZqurvpohpG3fFaguy0WEHBIY